# Project metadata
name: dbttest                  # main project name (lowercase & underscores)
version: '1.0.0'
config-version: 2
profile: dbttest               # your profile name

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # compiled SQL
clean-targets:
  - "target"
  - "dbt_packages"

# Default materialization (can be overridden in individual models)
models:
  dbttest:

    # ----- Old / Existing Batch Models -----
    DQ_QA_Module:
      +schema: dqlabs
      +materialized: view

    finance_model:
      +materialized: view

    property_model:
      +materialized: view

    redshift_models:
      +materialized: table

    snowflake_model:
      +schema: REPORTING
      +materialized: view

    sf_customer_model:
      +schema: CUSTOMERAI
      +materialized: view


    Demo_models:
      +schema: TARGET_DEMO
      +materialized: view

    Pipeline_Obs:
      +schema: banking_data_target
      +materialized: view

    snowflake-transformations:
      tags: ["snowflake-transformations"]
      +schema: REPORTING
      +materialized: view

    Snowflake_TL_SR: 
      +materialized: view
      +schema: DBT_MODLES

    # ----- New Real-Time Pipeline Models -----
    dbt_realtime_orders:
      staging:
        realtime:
          +schema: staging_rt
          +materialized: table
      intermediate:
        realtime:
          +schema: intermediate_rt
          +materialized: table
      marts:
        realtime:
          +schema: marts_rt
          +materialized: table
