{{
  config(
    materialized='table',
    tags=['gold', 'electronics']
  )
}}

WITH base AS (
  SELECT 
    RECORD_ID,
    "DATE" AS SALE_DATE,
    STORE_ID,
    PRODUCT_NAME,
    CATEGORY,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_AMOUNT,
    CUSTOMER_ID,
    SALES_REP,
    REGION,
    QUANTITY * UNIT_PRICE AS CALCULATED_TOTAL,
    CASE 
      WHEN TOTAL_AMOUNT != (QUANTITY * UNIT_PRICE) THEN 'PRICE_MISMATCH'
      ELSE 'PRICE_MATCH'
    END AS PRICE_VALIDATION,
    EXTRACT(YEAR FROM "DATE") AS SALE_YEAR,
    EXTRACT(MONTH FROM "DATE") AS SALE_MONTH,
    EXTRACT(DAY FROM "DATE") AS SALE_DAY,
    EXTRACT(QUARTER FROM "DATE") AS SALE_QUARTER,
    CASE 
      WHEN QUANTITY >= 10 THEN 'BULK_ORDER'
      WHEN QUANTITY >= 5 THEN 'MEDIUM_ORDER'
      ELSE 'SMALL_ORDER'
    END AS ORDER_SIZE,
    CASE 
      WHEN TOTAL_AMOUNT >= 1000 THEN 'HIGH_VALUE'
      WHEN TOTAL_AMOUNT >= 500 THEN 'MEDIUM_VALUE'
      ELSE 'LOW_VALUE'
    END AS ORDER_VALUE_CATEGORY
  FROM {{ ref('stg_retail_sales') }}
  WHERE CATEGORY = 'Electronics'
    AND PRODUCT_NAME IS NOT NULL
    AND QUANTITY > 0
    AND UNIT_PRICE > 0
    AND TOTAL_AMOUNT > 0
)

SELECT 
  RECORD_ID,
  SALE_DATE,
  STORE_ID,
  PRODUCT_NAME,
  CATEGORY,
  QUANTITY,
  UNIT_PRICE,
  TOTAL_AMOUNT,
  CUSTOMER_ID,
  SALES_REP,
  REGION,
  CALCULATED_TOTAL,
  PRICE_VALIDATION,
  SALE_YEAR,
  SALE_MONTH,
  SALE_DAY,
  SALE_QUARTER,
  ORDER_SIZE,
  ORDER_VALUE_CATEGORY,
  CURRENT_TIMESTAMP() AS LOADED_AT,
  '{{ invocation_id }}' AS DBT_RUN_ID
FROM base
