version: 2

models:
  - name: flight_passenger
    description: "Passenger by flight"
    columns:
      - name: flight_number
        description: "The unique identifier for the flight"
        tests:
          - not_null:
              config:
                severity: error
          # - unique:   # Uncomment if needed
          
  - name: passenger_airline
    description: "Passenger airline view"
    columns:
      - name: airline_id
        description: "Primary key of the airline"

  - name: passenger_flight
    description: "Passenger flight view"
    columns:
      - name: passenger_id
        description: "Primary key of the passenger"
      - name: flight_number
        description: "Foreign key to flight_passenger"
