version: 2

models:
  - name: fct_customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key

  - name: stg_orders1
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique:
              config:
                severity: error
          - not_null:
              config:
                severity: error
      - name: status
      - name: customer_id
        description: Foreign key to stg_customers
        tests:
          - not_null:
              config:
                severity: error
