version: 2

sources:
  - name: dqlabs_qa
    description: "DQLABS QA environment source tables"
    database: DQLABS_QA
    schema: STAGING
    tables:
      - name: retail_sales
        description: "Raw retail sales data from staging"
        columns:
          - name: RECORD_ID
            description: "Unique record identifier"
            tests:
             # - unique
              - not_null
          - name: "DATE"
            description: "Date of the sale"
            tests:
              - not_null
          - name: STORE_ID
            description: "Store identifier"
            tests:
              - not_null
          - name: PRODUCT_NAME
            description: "Name of the product sold"
            tests:
              - not_null
          - name: CATEGORY
            description: "Product category"
            tests:
              - not_null
          - name: CUSTOMER_ID
            description: "Customer identifier"
            tests:
              - not_null
          - name: SALES_REP
            description: "Sales representative"
            tests:
              - not_null
          - name: REGION
            description: "Sales region"
            tests:
              - not_null
