version: 2

models:
  - name: stg_orders
    columns:
      - name: ORDER_ID
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: CUSTOMER_ID
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

  - name: stg_customer
    columns:
      - name: CUSTOMER_ID
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
