version: 2
models:
  - name: product_sales_vw
    columns:
      - name: PRODUCTID
        tests:
          - unique
          - not_null
  - name: employee_sales_vw
    columns:
      - name: PRODUCTID
        tests:
          - unique
          - not_null