name: "DBT Impact Analysis on PR"

on:
  pull_request:
    paths:
      - '**/*.sql'
      - '**/*.yml'
      - '**/*.csv'
 
permissions:
  contents: read
  pull-requests: write
 
jobs:
  impact-analysis:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout PR code (head)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed DBT files
        id: changes
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.sql
            **/*.yml
            **/*.csv
          include_removed: true
          include_renamed: true
          separator: ","
 
      - name: Run PR impact analysis via dbt_mcp API
        id: impact-analysis
        env:
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DBT_MCP_BASE_URL: ${{ secrets.DBT_MCP_BASE_URL }}
          CLIENT_LINK_URL: ${{secrets.CLIENT_LINK_URL }}
          CHANGED_FILES: ${{ steps.changes.outputs.all_changed_files }},${{ steps.changes.outputs.deleted_files }}
          PRIZM_TOKEN: ${{ secrets.PRIZM_TOKEN }}
        run: |
          URL="${DBT_MCP_BASE_URL}/api/v1/dbt/github/pr-impact-analysis"
          echo "Calling API via POST: $URL"
          PAYLOAD=$(cat <<EOF
          {
            "repo": "$GITHUB_REPO",
            "pr_number": "$PR_NUMBER",
            "github_token": "$GITHUB_TOKEN",
            "prizm_configurable_keys": "indirect_asset_count,direct_asset_count,direct_asset_list, indirect_asset_list, direct_column_count, sql_column_changes,indirect_column_list,direct_column_list,total_impacted_models,total_impacted_assets,yml_column_changes",
            "changed_files_list": "$CHANGED_FILES",
            "client_link_url": "$CLIENT_LINK_URL"
          }
          EOF
          )
          echo "Payload:"
          echo "$PAYLOAD"
          echo "prizm_token"
          echo "$PRIZM_TOKEN"
          RESPONSE=$(curl -s -X POST "$URL" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${PRIZM_TOKEN}" \
            -d "$PAYLOAD")
          echo "API Response:"
          printf '%s\n' "$RESPONSE"
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          printf '%s\n' "$RESPONSE" > "$GITHUB_WORKSPACE/impact_api_response.json"
 
      - name: Show Summary in Logs
        run: cat "$GITHUB_WORKSPACE/impact_api_response.json"
 
      - name: Debug changed files
        run: |
          echo "All files: ${{ steps.changes.outputs.all_files }}"
          echo "Added files: ${{ steps.changes.outputs.added_files }}"
          echo "Modified files: ${{ steps.changes.outputs.modified_files }}"
          echo "Removed files: ${{ steps.changes.outputs.removed_files }}"
          echo "Renamed files: ${{ steps.changes.outputs.renamed_files }}"
          echo "All deleted_files	 files: ${{ steps.changes.outputs.deleted_files }}"
          echo "All deleted_files	 files: ${{ steps.changes.outputs }}"
          echo "Combined changed_files_list: ${{ steps.changes.outputs.all_changed_files }},${{ steps.changes.outputs.removed_files }}"
